version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: easypack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: capsuledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 可選：添加 pgAdmin 用於數據庫管理
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: easypack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@easypack.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: easypack-network
